### ISSUE TITLE
MySQL Support and config

### ISSUE THREAD

**Issue by Wertzui123** [ElementalMinecraftGaming/BanTime#2]
How would be a config where you cqn edit the messages? And MySQL Wupport for netwoks would be nice too.

**Comment by ElementalMinecraftGaming** [comment]
I'm planning on getting the reason part fixed to replace the message.
Not everyone is able to use MySQL but I'll think about it.

**Comment by Wertzui123** [comment]
I'm not able to use MySQL too, but I wan't to learn it. I think its very nice that there is a way to share data over your network

**Comment by LeoBdt** [comment]
MySQL is very easy to use. 

Can you add a broadcast when the player get banned?

**Comment by ElementalMinecraftGaming** [comment]
> MySQL is very easy to use.
> 
> Can you add a broadcast when the player get banned?

Sure

**Comment by Wertzui123** [comment]
Is it implemented?

**Comment by LeoBdt** [comment]
No

**Comment by Wertzui123** [comment]
Oked

**Comment by LeoBdt** [comment]
Yes it is, sorry.

**Comment by LeoBdt** [comment]
r u talking about broadcast system?

**Comment by Wertzui123** [comment]
No?

**Comment by ElementalMinecraftGaming** [comment]
> No?

MySQL is not supported in this plugin unfortunately and i don't have any plans for that. 
Apologies.

**Comment by Wertzui123** [comment]
:confused:
